### ISSUE TITLE
turbowarp support

### ISSUE THREAD

**Issue by JustablockCode** [nostopgmaming17/scratchSploit#1]
can you add tw support pls

**Comment by TheCommCraft** [comment]
wow

**Comment by Ryan-shamu-YT** [comment]
Bruh.

**Comment by Are-You-a-Person** [comment]
Add TurboWarp support yourself.

**Comment by JustablockCode** [comment]
nuh uh

lør. 25. mai 2024 kl. 05:20 skrev Are-You-a-Person ***@***.***

**Comment by noam00000** [comment]
i cant because turbowarp is compiled so doing stuff like hooking _primitives wouldnt work

**Comment by leothelino** [comment]
you can if you disable compiler, pls do it

**Comment by leothelino** [comment]
> i cant because turbowarp is compiled so doing stuff like hooking _primitives wouldnt work

you can if you disable compiler

**Comment by TheCommCraft** [comment]
Omg bro

**Comment by leothelino** [comment]
> Omg bro

but it doesnt work yet... please add support y'all

**Comment by TheCommCraft** [comment]
Why not add it yourself

leothelino ***@***.***> schrieb am Fr., 21. Feb. 2025, 10:57:

**Comment by leothelino** [comment]
> Why not add it yourself
> 
> leothelino ***@***.***> schrieb am Fr., 21. Feb. 2025, 10:57:
> […](#)

i suck at coding

**Comment by noam00000** [comment]
disabling compiler is really stupid since its the only feature tw has

**Comment by leothelino** [comment]
well, scratch's cloud servers are down a lot
