### ISSUE TITLE
not an issue but a question

### ISSUE THREAD

**Issue by Charlieis1nsan3** [nostopgmaming17/scratchSploit#10]
how does this work and what does it do?

**Comment by JustablockCode** [comment]
download extension


use one of js codes to cheat in game or make your own js code

you can also insert sprite into game without triggering scratch's thing that removes you from cloud and stuff

**Comment by Charlieis1nsan3** [comment]
no no no I know how to use it, but like did you abuse the websockets what's happening everytime I code a hack it disconnected

**Comment by Charlieis1nsan3** [comment]
and also would it be possible to  make it a bookmark let?

**Comment by Charlieis1nsan3** [comment]
is their any other ones too?

**Comment by v2-api** [comment]
you could make a very basic bookmarklet that just asked for a link to js or a sprite and injected it.
